import type { WebhookType } from "@/schemas/vercel";

export const EMOJIS = {
  SUCCESS: ":white_check_mark:",
  ERROR: ":x:",
  PENDING: ":hourglass_flowing_sand:",
  CANCELED: ":no_entry_sign:",
  PROMOTED: ":link:",
  BRANCH: ":seedling:",
  COMMIT: ":memo:",
  ENV: ":gear:",
  URL: ":globe_with_meridians:",
  DOMAIN: ":globe_with_meridians:",
  PROJECT: ":package:",
  NEW: ":new:",
  TRASH: ":wastebasket:",
  UPGRADE: ":arrow_up:",
  DISCONNECT: ":electric_plug:",
  CONNECT: ":link:",
  INVOICE: ":receipt:",
  WARNING: ":warning:",
  PAYMENT: ":moneybag:",
  MONEY: ":money_with_wings:",
  REFRESH: ":arrows_counterclockwise:",
  CLEANUP: ":broom:",
  CONFIRM: ":white_check_mark:",
  DEPLOY: ":rocket:",
  CERTIFICATE: ":closed_lock_with_key:",
  DNS: ":satellite_antenna:",
  TRANSFER: ":left_right_arrow:",
  ALERT: ":rotating_light:",
  ROLLING: ":arrows_counterclockwise:",
  RENAME: ":pencil2:",
  VERIFY: ":ballot_box_with_check:",
  UNVERIFY: ":grey_question:",
  MEMBER: ":bust_in_silhouette:",
} as const;

const STATE_EMOJI_MAP: Record<string, string> = {
  // Deployment events
  "deployment.canceled": EMOJIS.CANCELED,
  "deployment.check-rerequested": EMOJIS.REFRESH,
  "deployment.cleanup": EMOJIS.CLEANUP,
  "deployment.created": EMOJIS.PENDING,
  "deployment.error": EMOJIS.ERROR,
  "deployment.integration.action.cancel": EMOJIS.CANCELED,
  "deployment.integration.action.cleanup": EMOJIS.CLEANUP,
  "deployment.integration.action.start": EMOJIS.PENDING,
  "deployment.promoted": EMOJIS.PROMOTED,
  "deployment.ready": EMOJIS.SUCCESS,
  "deployment.succeeded": EMOJIS.SUCCESS,
  // Domain events
  "domain.created": EMOJIS.DOMAIN,
  "domain.auto-renew-changed": EMOJIS.REFRESH,
  "domain.certificate-add": EMOJIS.CERTIFICATE,
  "domain.certificate-add-failed": EMOJIS.ERROR,
  "domain.certificate-deleted": EMOJIS.TRASH,
  "domain.certificate-renew": EMOJIS.CERTIFICATE,
  "domain.certificate-renew-failed": EMOJIS.ERROR,
  "domain.dns-records-changed": EMOJIS.DNS,
  "domain.renewal": EMOJIS.SUCCESS,
  "domain.renewal-failed": EMOJIS.ERROR,
  "domain.transfer-in-completed": EMOJIS.SUCCESS,
  "domain.transfer-in-failed": EMOJIS.ERROR,
  "domain.transfer-in-started": EMOJIS.TRANSFER,
  // Project domain events
  "project.domain-created": EMOJIS.NEW,
  "project.domain-deleted": EMOJIS.TRASH,
  "project.domain-moved": EMOJIS.TRANSFER,
  "project.domain-unverified": EMOJIS.UNVERIFY,
  "project.domain-updated": EMOJIS.REFRESH,
  "project.domain-verified": EMOJIS.VERIFY,
  // Integration configuration events
  "integration-configuration.permission-upgraded": EMOJIS.UPGRADE,
  "integration-configuration.removed": EMOJIS.DISCONNECT,
  "integration-configuration.scope-change-confirmed": EMOJIS.CONFIRM,
  "integration-configuration.transferred": EMOJIS.TRANSFER,
  // Integration resource events
  "integration-resource.project-connected": EMOJIS.CONNECT,
  "integration-resource.project-disconnected": EMOJIS.DISCONNECT,
  // Marketplace events
  "marketplace.invoice.created": EMOJIS.INVOICE,
  "marketplace.invoice.notpaid": EMOJIS.WARNING,
  "marketplace.invoice.paid": EMOJIS.PAYMENT,
  "marketplace.invoice.refunded": EMOJIS.MONEY,
  "marketplace.member.changed": EMOJIS.MEMBER,
  // Alerts
  "alerts.triggered": EMOJIS.ALERT,
  // Project events
  "project.created": EMOJIS.NEW,
  "project.removed": EMOJIS.TRASH,
  "project.renamed": EMOJIS.RENAME,
  "project.rolling-release.approved": EMOJIS.SUCCESS,
  "project.rolling-release.completed": EMOJIS.SUCCESS,
  "project.rolling-release.aborted": EMOJIS.CANCELED,
  "project.rolling-release.started": EMOJIS.ROLLING,
  default: EMOJIS.DEPLOY,
};

export function getStateEmoji(type: WebhookType): string {
  return STATE_EMOJI_MAP[type] ?? STATE_EMOJI_MAP.default;
}
